/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package trias.klinika.client.Home;

import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author iqbal
 */
public class Splash extends javax.swing.JDialog {
    
    /**
     * Creates new form Splash
     */
    public Splash() {
        setUndecorated(true);
        initComponents();
        ProgBar.setStringPainted(true);
    }
    
    public void Awal() {
        Splash pertama = new Splash();
        pertama.setVisible(true);
        for(int i=0;i<=100;i++){
            try {
                pertama.ProgBar.setValue(i);
                Thread.sleep(40);
            }
            catch (InterruptedException ex) {
                Logger.getLogger(Splash.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        pertama.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ProgBar = new javax.swing.JProgressBar();
        progBar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Nyala", 3, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome to");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 160, 260, 53);

        jLabel2.setFont(new java.awt.Font("Nyala", 3, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Medical Solution");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 220, 360, 53);

        jLabel4.setFont(new java.awt.Font("Nyala", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Loading...");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(260, 380, 145, 39);

        jLabel5.setFont(new java.awt.Font("Nyala", 3, 55)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Trias - Klinika");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, 280, 340, 40);

        ProgBar.setBackground(new java.awt.Color(255, 255, 255));
        ProgBar.setFont(new java.awt.Font("Nyala", 3, 18)); // NOI18N
        ProgBar.setForeground(new java.awt.Color(0, 153, 0));
        getContentPane().add(ProgBar);
        ProgBar.setBounds(10, 460, 1350, 30);

        progBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/splash.png"))); // NOI18N
        getContentPane().add(progBar);
        progBar.setBounds(0, 0, 1366, 768);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel progBar;
    // End of variables declaration//GEN-END:variables
}
