/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package trias.klinika.client.apotek;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import trias.klinika.api.entitas.InventoryObatApotekEntitas;
import trias.klinika.api.sevice.InventoryObatApotekService;
import trias.klinika.client.tabel.tabelInventoryObatApotek;
/**
 *
 * @author Azmil
 */
public class InventoryObatApotek extends javax.swing.JInternalFrame {
    
    int z;
    private InventoryObatApotekService IOAS;
    private String [] isi;
    private String [] sp ;
    private tabelInventoryObatApotek tioa = new tabelInventoryObatApotek();
    private String aiObat;
    private int aiDetail;
    private int index;

//    private String [] jenis;
//    private String [] spesialis;
    /**
     * Creates new form InventoryObatApotek
     */
        public InventoryObatApotek(InventoryObatApotekService IOAS) throws RemoteException {
            
        
        this.IOAS = IOAS;
        tioa.setData(this.IOAS.getobat());// harusnyya pake try
        initComponents();
        
        Dropdown();
        table_obat.setModel(tioa);
        table_obat.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged (ListSelectionEvent e){
                int row = table_obat.getSelectedRow();
                if (row != -1) {
                    InventoryObatApotekEntitas IOAE = tioa.get(row);                    
                    
                    nama_obat.setText(IOAE.getNamaObat());
                    qty.setText(Integer.toString(IOAE.getQty()));
                    harga.setText(Integer.toString(IOAE.getHargaObat()));
                    deskripsi.setText(IOAE.getDeskripsi()); 
                    tgl_masuk.setDate(Date.valueOf(IOAE.getTglMasuk()));
                    masa_pakai.setDate(Date.valueOf(IOAE.getMasaPakai()));
                    for (int i=0; i<jenis_obat.getItemCount();i++){
                        
                        if(jenis_obat.getItemAt(i).toString().substring(7).equals(IOAE.getJenisObat())){
                            index=i;
                        }    
                    }
                    jenis_obat.setSelectedItem(jenis_obat.getItemAt(index));
                    index = 0;
                    for (int i=0; i<spesialis.getItemCount();i++){
                        if(spesialis.getItemAt(i).toString().substring(6).equals(IOAE.getNamaSpesialis())){
                            index=i;
                        }
                    }
                    spesialis.setSelectedItem(spesialis.getItemAt(index));
                    }
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nama_obat = new javax.swing.JTextField();
        qty = new javax.swing.JTextField();
        tgl_masuk = new com.toedter.calendar.JDateChooser();
        masa_pakai = new com.toedter.calendar.JDateChooser();
        harga = new javax.swing.JTextField();
        deskripsi = new javax.swing.JTextField();
        jenis_obat = new javax.swing.JComboBox();
        spesialis = new javax.swing.JComboBox();
        cekkritis = new javax.swing.JButton();
        kadaluarsa = new javax.swing.JButton();
        input = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        tabel = new javax.swing.JScrollPane();
        table_obat = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(1147, 570));
        setPreferredSize(new java.awt.Dimension(1147, 570));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("INVENTORY OBAT APOTEK");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(547, 11, 200, 20);

        jLabel4.setText("Nama Obat");

        jLabel6.setText("Jenis Obat");

        jLabel7.setText("Quantity");

        jLabel8.setText("Tanggal Masuk");

        jLabel9.setText("Masa Pakai");

        jLabel10.setText("Spesialisasi");

        jLabel5.setText("Harga Obat");

        jLabel11.setText("Deskripsi Obat");

        nama_obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_obatActionPerformed(evt);
            }
        });

        deskripsi.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jenis_obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenis_obatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deskripsi))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spesialis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(masa_pakai, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(tgl_masuk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(harga)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jenis_obat, javax.swing.GroupLayout.Alignment.TRAILING, 0, 255, Short.MAX_VALUE)
                            .addComponent(nama_obat, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(qty, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama_obat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jenis_obat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(tgl_masuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(masa_pakai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(spesialis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(deskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 38, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(650, 30, 350, 414);

        cekkritis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cekkritis.setForeground(new java.awt.Color(0, 0, 204));
        cekkritis.setText("Cek Kritis");
        cekkritis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekkritisActionPerformed(evt);
            }
        });
        getContentPane().add(cekkritis);
        cekkritis.setBounds(1000, 40, 113, 23);

        kadaluarsa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kadaluarsa.setForeground(new java.awt.Color(0, 0, 255));
        kadaluarsa.setText("Cek Kadaluarsa");
        kadaluarsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kadaluarsaActionPerformed(evt);
            }
        });
        getContentPane().add(kadaluarsa);
        kadaluarsa.setBounds(1000, 80, 113, 23);

        input.setForeground(new java.awt.Color(0, 0, 153));
        input.setText("Input");
        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });
        getContentPane().add(input);
        input.setBounds(1000, 120, 113, 23);

        tambah.setForeground(new java.awt.Color(0, 0, 255));
        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah);
        tambah.setBounds(1000, 160, 113, 23);

        delete.setForeground(new java.awt.Color(0, 51, 255));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(1000, 200, 113, 23);

        update.setForeground(new java.awt.Color(0, 51, 204));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(1000, 240, 113, 23);

        clear.setForeground(new java.awt.Color(0, 51, 204));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(1000, 280, 113, 23);

        table_obat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.setViewportView(table_obat);

        getContentPane().add(tabel);
        tabel.setBounds(20, 40, 606, 383);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nama_obatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_obatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_obatActionPerformed

    private void jenis_obatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenis_obatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenis_obatActionPerformed

    private void cekkritisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekkritisActionPerformed
        setCekKritis();
// TODO add your handling code here:
    }//GEN-LAST:event_cekkritisActionPerformed

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed

        JOptionPane.showConfirmDialog(null, "Apakah anda sudah yakin?","", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(nama_obat.getText()==""|qty.getText()==""|harga.getText()==""|tgl_masuk.getDate()==null|masa_pakai.getDate()==null|deskripsi.getText()==""){
            JOptionPane.showMessageDialog(this, "Salah Satu Data Belum di Isi");
        }
        else{
            
            InventoryObatApotekEntitas IOAE = null;
            try {
                IOAE = setInputObat(auto_increment_obat (),auto_increment_detail ());
            } catch (RemoteException ex) {
                Logger.getLogger(InventoryObatApotek.class.getName()).log(Level.SEVERE, null, ex);
            }
            tioa.insert(IOAE);
            try {
            IOAS.insertObatBaru(IOAE);
            refresh();
            }
            catch (RemoteException ex){
                Logger.getLogger(InventoryObatApotek.class.getName()).log(Level.SEVERE, null, ex);
            }
// harusnya pake try
        }
    }//GEN-LAST:event_inputActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        JOptionPane.showConfirmDialog(null, "Apakah anda sudah yakin?","", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(qty.getText()==""|tgl_masuk.getDate()==null|masa_pakai.getDate()==null){
            JOptionPane.showMessageDialog(this, "Salah Satu Data Belum di Isi");
        }
        else{
            InventoryObatApotekEntitas IOAE = null;
            aiObat = tioa.get(table_obat.getSelectedRow()).getIdObat();
            System.out.println(aiObat);
            try {
                IOAE = setTambahObat(aiObat,auto_increment_detail());
            } catch (RemoteException ex) {
                Logger.getLogger(InventoryObatApotek.class.getName()).log(Level.SEVERE, null, ex);
            }

            tioa.tambah(IOAE);
            try {
            IOAS.tambahObat(IOAE);
            refresh();
            }
            catch (RemoteException ex){
                Logger.getLogger(InventoryObatApotek.class.getName()).log(Level.SEVERE, null, ex);
            }
// harusnya pake try
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        InventoryObatApotekEntitas IOAE = new InventoryObatApotekEntitas();
        JOptionPane.showConfirmDialog(null, "Apakah anda sudah yakin?","", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        try{
        int row = table_obat.getSelectedRow();
        if(row == -1){
            return;
        }
        tioa.delete(IOAE);
        
        IOAS.deleteObat(IOAE);
        refresh();
        }
       catch (RemoteException exception){
        JOptionPane.showMessageDialog(this, "Proses Penghapusan obat berhasil");    
        }
        
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        JOptionPane.showConfirmDialog(null, "Apakah anda sudah yakin?","", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        // TODO add your handling code here:
        InventoryObatApotekEntitas IOAE = new InventoryObatApotekEntitas ();
        setUpdateObat();
        tioa.update(IOAE);
        try{
        IOAS.updateObat(IOAE);
        refresh();
        //PreparedStatement statement = new PreparedStatement();
        }
        catch (RemoteException ex){
                Logger.getLogger(InventoryObatApotek.class.getName()).log(Level.SEVERE, null, ex);
            }
        JOptionPane.showMessageDialog(this, "Proses Update Obat Berhasil");
        
    }//GEN-LAST:event_updateActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        
        
        nama_obat.setText("");
        qty.setText("");
        harga.setText("");
        deskripsi.setText("");
        tgl_masuk.setDate(null);
        masa_pakai.setDate(null);
        jenis_obat.setSelectedItem(jenis_obat.getItemAt(0));
        spesialis.setSelectedItem(spesialis.getItemAt(0));
        // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void kadaluarsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kadaluarsaActionPerformed
        setCekExpired();
    }//GEN-LAST:event_kadaluarsaActionPerformed
    private void refresh (){
        try {
            List<InventoryObatApotekEntitas> list = IOAS.getobat();
            tioa.setData(list);
        } catch (RemoteException exception) {
            exception.printStackTrace();
        }
    }
    private void Dropdown () throws RemoteException{
        isi = IOAS.DropdownJenis(isi);
        sp = IOAS.DropdownSpesialis(sp);
        for (int i=0;i<isi.length;i++){
            jenis_obat.addItem(isi[i]);
        }
        for (int i=0;i<sp.length;i++){
            spesialis.addItem(sp[i]);
        }
    }
    public InventoryObatApotekEntitas setTambahObat (String aiObat, int aiDetail){
        InventoryObatApotekEntitas IOAE = new InventoryObatApotekEntitas();

            IOAE.setQty(Integer.parseInt(qty.getText()));
            IOAE.setTglMasuk(tgl_masuk.getDate().toString());
            IOAE.setMasaPakai(masa_pakai.getDate().toString());
            IOAE.setRuangObat("Apotek");
            java.util.Date date = new java.util.Date(tgl_masuk.getDate().getTime());
            
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String tgl = sdf.format(date);
            IOAE.setTglMasuk(tgl);
            
            java.util.Date date1 = new java.util.Date(masa_pakai.getDate().getTime());
            SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
            String tgl1 = sdf1.format(date1);
            IOAE.setMasaPakai(tgl1);
            IOAE.setIdObat(aiObat);
            IOAE.setIdDetailObat(aiDetail);
            return IOAE;
    }
    public InventoryObatApotekEntitas setInputObat(String aiObat, int aiDetail){
        InventoryObatApotekEntitas IOAE = new InventoryObatApotekEntitas();
            IOAE.setIdObat(aiObat);
            IOAE.setNamaObat(nama_obat.getText());
            IOAE.setQty(Integer.parseInt(qty.getText()));
            IOAE.setTglMasuk(tgl_masuk.getDate().toString());
            IOAE.setMasaPakai(masa_pakai.getDate().toString());
            IOAE.setDeskripsi(deskripsi.getText());
            IOAE.setRuangObat("Apotek");
            IOAE.setIdSpesialis(spesialis.getSelectedItem().toString().substring(0,5));
            IOAE.setHargaObat(Integer.parseInt(harga.getText()));
            IOAE.setIdJenisObat(jenis_obat.getSelectedItem().toString().substring(0,6));
            IOAE.setIdDetailObat(aiDetail);
            java.util.Date date = new java.util.Date(tgl_masuk.getDate().getTime());
            
            SimpleDateFormat SDF = new SimpleDateFormat("yyyy-MM-dd");
            String tgl2 = SDF.format(date);
            IOAE.setTglMasuk(tgl2);
            
            java.util.Date date2 = new java.util.Date(masa_pakai.getDate().getTime());
            SimpleDateFormat SDF2 = new SimpleDateFormat("yyyy-MM-dd");
            String tgl3 = SDF2.format(date2);
            IOAE.setMasaPakai(tgl3);
            return IOAE;
            
    }
    public void setUpdateObat (){
        InventoryObatApotekEntitas IOAE = new InventoryObatApotekEntitas();
        IOAE.setDeskripsi(deskripsi.getText());
        java.util.Date date1 = new java.util.Date(masa_pakai.getDate().getTime());
            SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
            String tgl1 = sdf1.format(date1);
            IOAE.setMasaPakai(tgl1);
        java.util.Date date = new java.util.Date(tgl_masuk.getDate().getTime());
            System.out.println(date.toString());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String tgl = sdf.format(date);
            IOAE.setTglMasuk(tgl);
            System.out.println(tgl);
        IOAE.setHargaObat(Integer.parseInt(harga.getText()));  
    }
    public void setCekKritis(){
        try {
            List<InventoryObatApotekEntitas> list = IOAS.cekKritis();
            tioa.removeTableModelListener(table_obat);
            tioa.setData(list);
            table_obat.setModel(tioa);
        } catch (RemoteException exception) {
            exception.printStackTrace();
        }
    }
    public void setCekExpired (){
        try {
            List<InventoryObatApotekEntitas> list = IOAS.cekExpired();
            tioa.setData(list);
        } catch (RemoteException exception) {
            exception.printStackTrace();
        }
    }
    private String auto_increment_obat () throws RemoteException { 
       return IOAS.auto_increment_idobat(aiObat);
    }
    private int auto_increment_detail () throws RemoteException {
        return IOAS.auto_increment_iddetail(aiObat);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cekkritis;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JTextField deskripsi;
    private javax.swing.JTextField harga;
    private javax.swing.JButton input;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox jenis_obat;
    private javax.swing.JButton kadaluarsa;
    private com.toedter.calendar.JDateChooser masa_pakai;
    private javax.swing.JTextField nama_obat;
    private javax.swing.JTextField qty;
    private javax.swing.JComboBox spesialis;
    private javax.swing.JScrollPane tabel;
    private javax.swing.JTable table_obat;
    private javax.swing.JButton tambah;
    private com.toedter.calendar.JDateChooser tgl_masuk;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
