package trias.klinika.client.reservasi;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Container;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.MouseListener;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.*;
import trias.klinika.api.sevice.DokterService;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import trias.klinika.api.entitas.LoginEntitas;
import trias.klinika.api.sevice.PendaftaranService;
import trias.klinika.api.sevice.ListPembayaranService;
import trias.klinika.api.sevice.PasienService;
import trias.klinika.client.tabel.TabelDokter;

/**
 *
 * @author Lenovo
 */
public class utamaReservasi extends javax.swing.JFrame {
    
    String localhost = this.getTitle();
    private TabelDokter tabeldokter = new TabelDokter();
    Registry registry = LocateRegistry.getRegistry(localhost, 4444);
    final  PendaftaranService service2 = (PendaftaranService)registry.lookup("service2");
    final  ListPembayaranService service12 = (ListPembayaranService)registry.lookup("service12");
    final  DokterService service3 = (DokterService)registry.lookup("service3");
    final  PasienService service7 = (PasienService)registry.lookup("service7");
    Antrean Pe = new Antrean(service3,service7);
    private DokterService DS;
    private PasienService PaSer;
    TriasKlinika_Pendaftaran daft = new TriasKlinika_Pendaftaran(service2);
    TriasKlinika_ListPembayaran LP = new TriasKlinika_ListPembayaran(service12);
    private ListPembayaranService LPS;
    private PendaftaranService PS;
    private String[] isi;
    LoginEntitas LE;
    private JInternalFrame internalFrame1 = new JInternalFrame("Frame Antrean");
    private JInternalFrame internalFrame2 = new JInternalFrame("Frame Pendaftaran");
    private JInternalFrame internalFrame3 = new JInternalFrame("Frame List Pembayaran");
    /**
     * Creates new form Utama
     */
    
//    public static void main(String[] args) {
//        // TODO code application logic here
//        try {
//        UIManager.setLookAndFeel("com.jtattoo.plaf.mint.MintLookAndFeel");
//        SwingUtilities.updateComponentTreeUI(new Utama());
//        } catch (Exception e){
// 
//        }
//        new Utama().setVisible(true);
//    }
    
    public utamaReservasi(LoginEntitas LE)throws RemoteException,NotBoundException {
        this.LE = LE;
        initComponents();
        internal_frame();
        nama.setText(LE.getnamauser());
        Dimension dim = (Toolkit.getDefaultToolkit()).getScreenSize();
        setSize(dim);
        
        ImageIcon ico = new ImageIcon("src/image/imin.png");
        setIconImage(ico.getImage());
 
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
        (screenSize.width - frameSize.width) / 2,
        (screenSize.height - frameSize.height) / 2);
   
//        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        nama = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);

        jDesktopPane2.setMinimumSize(new java.awt.Dimension(1147, 557));

        jToggleButton1.setText("Antrean");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Pendaftaran");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton3.setText("List Pembayaran");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 391, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        nama.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nama.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nama)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(nama)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        try
        {
            jDesktopPane2.removeAll();
            jDesktopPane2.add(internalFrame2);
            System.out.println("2");
            BasicInternalFrameUI ui = (BasicInternalFrameUI)internalFrame2.getUI();
            Container north = (Container)ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();
            System.out.println("3");
            for(MouseListener listener : ((javax.swing.plaf.basic.BasicInternalFrameUI) internalFrame2.getUI()).getNorthPane().getMouseListeners()){
                ((javax.swing.plaf.basic.BasicInternalFrameUI) internalFrame2.getUI()).getNorthPane().removeMouseListener(listener);
            }
            internalFrame2.setSelected(true);

        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
            System.out.println("syeemangat choy");
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            //        Kecil satu = new Kecil();
            //        Besar dua = new Besar();
            //        jDesktopPane1.add(imin);
            //        imin.setVisible(true);
            //            Pe.setTitle(this.getTitle());
            //            Pe.setVisible(true);

            //            JComboBox JCB = new JComboBox();
            //            isi = DS.Dropdowndokter(isi);
            //        for (int i=0;i<isi.length;i++){
                //            JCB.addItem(isi[i]);
                //        }
            jDesktopPane2.removeAll();
            jDesktopPane2.add(internalFrame1);
            //           internalFrame1.setClosable(true);
            System.out.println("2");
            BasicInternalFrameUI ui = (BasicInternalFrameUI)internalFrame1.getUI();
            Container north = (Container)ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();
            System.out.println("3");
            for(MouseListener listener : ((javax.swing.plaf.basic.BasicInternalFrameUI) internalFrame1.getUI()).getNorthPane().getMouseListeners()){
                ((javax.swing.plaf.basic.BasicInternalFrameUI) internalFrame1.getUI()).getNorthPane().removeMouseListener(listener);
            }
            internalFrame1.setSelected(true);

        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
            System.out.println("syeemangat choy");
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
        try
        {
            jDesktopPane2.removeAll();
            jDesktopPane2.add(internalFrame3);
            System.out.println("2");
            BasicInternalFrameUI ui = (BasicInternalFrameUI)internalFrame3.getUI();
            Container north = (Container)ui.getNorthPane();
            north.remove(0);
            north.validate();
            north.repaint();
            System.out.println("3");
            for(MouseListener listener : ((javax.swing.plaf.basic.BasicInternalFrameUI) internalFrame3.getUI()).getNorthPane().getMouseListeners()){
                ((javax.swing.plaf.basic.BasicInternalFrameUI) internalFrame3.getUI()).getNorthPane().removeMouseListener(listener);
            }
            internalFrame3.setSelected(true);

        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
            System.out.println("syeemangat choy");
        }
    }//GEN-LAST:event_jToggleButton3ActionPerformed
    public void internal_frame (){
        
           internalFrame1.add(Pe.getContentPane());
        
           internalFrame1.pack();
         
           internalFrame1.setSize(1146,577);
         
           internalFrame1.setVisible(true);
     
     
           internalFrame2.add(daft.getContentPane());
    
           internalFrame2.pack();
      
           internalFrame2.setSize(1146,577);
 
           internalFrame2.setVisible(true);
           
           internalFrame3.add(LP.getContentPane());
    
           internalFrame3.pack();
      
           internalFrame3.setSize(1146,577);
 
           internalFrame3.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JLabel nama;
    // End of variables declaration//GEN-END:variables
}
